"""Gaussian-correlated radius disorder on a periodic chain of N cells.

Target covariance C(m) = sigma^2 exp(-m_p^2 / (2 lc^2)) with the ring distance
m_p = min(m, N - m); lc = 0 is white noise. Samples are generated by circulant
spectral synthesis: with numpy's unnormalised FFT a stationary periodic sequence
with covariance C has E|X_j|^2 = N S_j, S = FFT(C), so filtering unit white
noise by sqrt(S) reproduces C exactly in the ensemble. The Gaussian kernel on a
ring is not always positive definite; negative spectral values are set to zero
and the spectrum is rescaled to restore mean(S) = sigma^2.
"""
import numpy as np


def target_cov(N, sigma, lc):
    m = np.arange(N)
    mp = np.minimum(m, N - m).astype(float)
    if lc <= 0:
        return sigma ** 2 * (mp == 0).astype(float)
    return sigma ** 2 * np.exp(-mp ** 2 / (2 * lc ** 2))


def psd_raw(N, sigma, lc):
    return np.fft.fft(target_cov(N, sigma, lc)).real


def psd_clip_weight(N, sigma, lc):
    """Fraction of the spectral weight removed by the positivity clip."""
    S = psd_raw(N, sigma, lc)
    total = float(np.abs(S).sum())
    return float(-S[S < 0].sum() / total) if total > 0 else 0.0


def psd(N, sigma, lc):
    S = np.clip(psd_raw(N, sigma, lc), 0.0, None)
    mean = S.mean()
    if mean <= 0:
        raise ValueError("degenerate spectrum")
    return S * (sigma ** 2 / mean)


def sample(N, sigma, lc, rng):
    S = psd(N, sigma, lc)
    w = rng.standard_normal(N)
    return np.fft.ifft(np.sqrt(S) * np.fft.fft(w)).real


def sample_autocov(n_samples, N, sigma, lc, rng):
    """Ensemble autocovariance estimated from n_samples realisations."""
    acc = np.zeros(N)
    for _ in range(n_samples):
        x = sample(N, sigma, lc, rng)
        acc += np.fft.ifft(np.abs(np.fft.fft(x)) ** 2).real / N
    return acc / n_samples
